
local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "deDE", true)

if not L then return end

-- Delves
L["Sturdy Chest"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest Note"] = "|cFFFFFFFFÖffne die Stabile Truhe|r"
L["Sturdy Chest 1"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 1 Note"] = "Springe vom zweiten Stockwerk auf den Kran und gehe nach vorne."
L["Sturdy Chest 2"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 2 Note"] = "Dieser Ort kann erreicht werden, indem man von der Steinplattform in der Nähe des Eingangs springt."
L["Sturdy Chest 3"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 3 Note"] = "Dieses Gebiet kann erreicht werden, indem man vom Schiff des Bosses springt."
L["Sturdy Chest 4"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 4 Note"] = "Es befindet sich auf einem Sims über dem Raum. Es gibt einen Greifpunkt, um dorthin zu gelangen. Während der Quest |cFF1EFF00Alles Liebe von der Weberin|r."
L["Sturdy Chest 5"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 5 Note"] = "Nach dem Boss, springe nicht in das Loch, sondern überprüfe die Säule unterhalb westlich des Hauptwegs."
L["Sturdy Chest 6"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 6 Note"] = "Unmittelbar nach Truhe 3, springe hinunter auf das hölzerne Sims unten im Westen."
L["Sturdy Chest 7"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 7 Note"] = "Auf einer kleinen Plattform unter dem Hauptweg."
L["Sturdy Chest 8"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 8 Note"] = "Gehe um den Schatzraum herum und den Pfad hinauf. Überprüfe einen Busch dort oben."
L["Sturdy Chest 9"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 9 Note"] = "Unter Wasser - enthält das |cFF0070DDAltes Konstrukt|r-Spielzeug."
L["Sturdy Chest 10"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 10 Note"] = "Ein Pilz, der dir hilft, zur letzten Truhe zu springen."
L["Sturdy Chest 11"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 11 Note"] = "Springe auf das Gerüst."
L["Sturdy Chest 12"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 12 Note"] = "Unter Wasser"
L["Sturdy Chest 13"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 13 Note"] = "Während der Quest |cFF1EFF00Weber Rettung|r."
L["Sturdy Chest 14"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 14 Note"] = "Während der Quest |cFF1EFF00Folteropfer|r."
L["Sturdy Chest 15"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 15 Note"] = "An der Latte."
L["Sturdy Chest 16"] = "|cFFFFFFFFSpringen|r"
L["Sturdy Chest 16 Note"] = "Von hier springen."
L["Sturdy Chest 17"] = "|cFFFFFFFFSpringen|r"
L["Sturdy Chest 17 Note"] = "Von hier springen."
L["Sturdy Chest 18"] = "|cFFFFFFFFStabile Truhe|r"
L["Sturdy Chest 18 Note"] = "Verwenden |cFF1EFF00Phasenschneider|r."
L["Sturdy Chest 19"] = "|cFFFFFFFFSpringen|r"
L["Sturdy Chest 19 Note"] = "Klettere auf die Wurzeln und folge dem schmalen Pfad."


L["Ancient Chest #1"] = "|cFFFFFFFFUralte Truhe #1|r"
L["Ancient Chest #2"] = "|cFFFFFFFFUralte Truhe #2|r"
L["Ancient Chest #3"] = "|cFFFFFFFFUralte Truhe #3|r"
L["Ancient Chest #4"] = "|cFFFFFFFFUralte Truhe #4|r"
L["Ancient Chest #5"] = "|cFFFFFFFFUralte Truhe #5|r"
L["Ancient Chest #6"] = "|cFFFFFFFFUralte Truhe #6|r"
L["Ancient Chest #7"] = "|cFFFFFFFFUralte Truhe #7|r"
L["Ancient Chest #8"] = "|cFFFFFFFFUralte Truhe #8|r"
L["Ancient Chest #9"] = "|cFFFFFFFFUralte Truhe #9|r"
L["Ancient Chest #10"] = "|cFFFFFFFFUralte Truhe #10|r"
L["Ancient Chest #11"] = "|cFFFFFFFFUralte Truhe #11|r"
L["Ancient Chest #12"] = "|cFFFFFFFFUralte Truhe #12|r"
L["Ancient Chest #13"] = "|cFFFFFFFFUralte Truhe #13|r"
L["Ancient Chest #14"] = "|cFFFFFFFFUralte Truhe #14|r"
L["Ancient Chest #15"] = "|cFFFFFFFFUralte Truhe #15|r"
L["Ancient Chest #16"] = "|cFFFFFFFFUralte Truhe #16|r"
L["Ancient Chest #17"] = "|cFFFFFFFFUralte Truhe #17|r"
L["Ancient Chest #18"] = "|cFFFFFFFFUralte Truhe #18|r"
L["Ancient Chest #19"] = "|cFFFFFFFFUralte Truhe #19|r"
L["Ancient Chest #20"] = "|cFFFFFFFFUralte Truhe #20|r"
L["Ancient Chest #21"] = "|cFFFFFFFFUralte Truhe #21|r"
L["Ancient Chest #22"] = "|cFFFFFFFFUralte Truhe #22|r"
L["Ancient Chest #23"] = "|cFFFFFFFFUralte Truhe #23|r"
L["Ancient Chest #24"] = "|cFFFFFFFFUralte Truhe #24|r"
L["Ancient Chest #25"] = "|cFFFFFFFFUralte Truhe #25|r"
L["Ancient Chest #26"] = "|cFFFFFFFFUralte Truhe #26|r"
L["Ancient Chest #27"] = "|cFFFFFFFFUralte Truhe #27|r"
L["Ancient Chest #28"] = "|cFFFFFFFFUralte Truhe #28|r"
L["Ancient Chest #29"] = "|cFFFFFFFFUralte Truhe #29|r"
L["Ancient Chest #30"] = "|cFFFFFFFFUralte Truhe #30|r"
L["Ancient Chest #31"] = "|cFFFFFFFFUralte Truhe #31|r"
L["Ancient Chest #32"] = "|cFFFFFFFFUralte Truhe #32|r"
L["Ancient Chest #33"] = "|cFFFFFFFFUralte Truhe #33|r"
L["Ancient Chest #34"] = "|cFFFFFFFFUralte Truhe #34|r"
L["Ancient Chest #35"] = "|cFFFFFFFFUralte Truhe #35|r"
L["Ancient Chest #36"] = "|cFFFFFFFFUralte Truhe #36|r"
L["Ancient Chest #37"] = "|cFFFFFFFFUralte Truhe #37|r"
L["Ancient Chest #38"] = "|cFFFFFFFFUralte Truhe #38|r"

L["Entrance"] = "Eingang bei 56.9, 34.4"

-- Wegpunkte
L["Create waypoint"] = "Wegpunkt erstellen"
L["Create all waypoints"] = "Alle Wegpunkte erstellen"
L["Hide node"] = "Knotenpunkt ausblenden"
L["Close"] = "Schließen"

-- Optionen
L["Icon settings"] = "Icon Einstellungen"
L["These settings control the look of the icon."] = "Diese Einstellungen steuern das Aussehen des Icons."
L["Icon Scale"] = "Icon-Skalierung"
L["The scale of the icons"] = "Die Skalierung der Icons"
L["Icon Alpha"] = "Icon-Alpha"
L["The alpha transparency of the icons"] = "Die Alpha-Transparenz der Icons"
L["World Map"] = "Weltkarte"
L["Show icons on world map"] = "Icons auf der Weltkarte anzeigen"
L["Minimap"] = "Minikarte"
L["Show icons on the minimap"] = "Icons auf der Minikarte anzeigen"
L["What to display"] = "Was angezeigt werden soll"
L["Show Zamros"] = "Goldfarmen-Standorte anzeigen"
L["Show Zamros gold"] = "Aktivitätspunkte anzeigen, mit denen du Gold verdienen kannst"